### PR TITLE
Add automatic submodules and theirs npm deps install

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Comment by xtuc** [comment]
Cool :+1:

I used [`npm install test262-harness`](https://github.com/xtuc/babel-test262/blob/master/.travis.yml#L6) in the CI.

Do you know the difference?

**Comment by chicoxyzzy** [comment]
I think that it's just easier to install the whole project on any computer (including local) by just running `npm i`

**Comment by chicoxyzzy** [comment]
Oh sorry I didn't understand you correctly. Yes I think we can use `npm install` there.

Do you publish your fork on npm manually?

**Comment by chicoxyzzy** [comment]
I think it's better to make things consistent between local environments and CI. Travis runs `npm install` automatically, right? Is it OK if I'll remove `before_install` from Travis config?

**Comment by xtuc** [comment]
Yes, sounds great. Could you update it in that PR?

**Pull request merged**
